### ISSUE TITLE
META - Documentation improvements (infra and workflows)

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#397]
Docusaurus allows us to create landing pages, and provides a nice visual and functional user experience for the docs. For example, see Nebari docs update: https://www.nebari.dev/

From Tania:
> If we move to Docusaurus we could even add the [Storybook Docusaurus addon](https://storybook.js.org/addons/storybook-addon-docusaurus/) to keep all our docs in a single place

---

```[tasklist]
### Tasks
- [x] Set up Docusaurus docs site for conda-store - #534
- [x] Set up docs framework - #398
- [ ] https://github.com/conda-incubator/conda-store/issues/690
- [x] Update relevant repo files to point to new docs
- [ ] https://github.com/conda-incubator/conda-store/issues/570
- [x] Deploy new docs - need to clarify, related: #407
- [x] Remove old Sphinx docs (and dependencies) #695
- [x] Update docs home page messaging+design - #565
- [x] Update theme to match conda-store design
- [ ] https://github.com/conda-incubator/conda-store/issues/699
- [x] Close/delete RTD deployment for conda-store
```

**Comment by costrouc** [comment]
@pavithraes I am open to this but do appreciate the "simplicity" of sphinx. I feel this would be a lot of work to make that transition. That said I do think that the docusuarus generated pages are much nicer.

**Comment by trallard** [comment]
If we move to Docusaurus we could even add  the [Storybook Docusaurus addon](https://storybook.js.org/addons/storybook-addon-docusaurus/) to keep all our docs in a single place

**Comment by costrouc** [comment]
@pavithraes clould you write a status update on this?

**Comment by costrouc** [comment]
@smeragoel asked if it is possible to document design here as well?

**Comment by pavithraes** [comment]
@costrouc - this work was on hold for a while, picking it up this week. :)

> @smeragoel asked if it is possible to document design here as well?

I don't fully understand the question here, could you please elaborate on this @smeragoel?
In case you mean should we track it here -- there is a task for design doc in #561 (tracking the actual content there) and the placeholder page is: https://github.com/conda-incubator/conda-store/blob/main/docusaurus-docs/community/design.md

**Comment by pavithraes** [comment]
I'm going to mark this META issue as complete. We do have the playwright tests task remaining, but we can track that in the corresponding issue. :)
