### ISSUE TITLE
META - Improve local experience of conda-store

### ISSUE THREAD

**Issue by trallard** [conda-incubator/conda-store#506]
## Background

conda-store has a `--standalone` flag that allows the user to run conda-store locally without needing access to remote infrastructure or a remote DB. 

For this first Quarter of the JATIC project, the team will be working on improving the local experience for conda-store and conda-store-ui.

Some high-level tasks identified:

```[tasklist]
### Tasks
- [ ] https://github.com/Quansight/conda-store/issues/513
- [x] Revisit docker-compose implementation
- [ ] https://github.com/conda-incubator/conda-store/issues/552
``` 

## Resources 🔗 

- [docker-compose PR](https://github.com/Quansight/conda-store-ui/pull/48)

**Comment by kcpevey** [comment]
Currently we can deploy local conda-store on Mac and linux. Work continues on Windows.
