### ISSUE TITLE
TASK - Post org migration tasks

### ISSUE THREAD

**Issue by trallard** [conda-incubator/conda-store#514]
Now that we have migrated the repository to the conda-incubator organisation there are several follow-up tasks to complete:

```[tasklist]
### Tasks
- [ ] https://github.com/conda-incubator/conda-store/issues/532
- [x] Update `.github/workflows` as needed - https://github.com/conda-incubator/conda-store/pull/525
- [x] Update issue and PR templates in the repository - https://github.com/conda-incubator/conda-store/pull/521
- [x] Ensure the repo points to the conda CoC - https://github.com/conda-incubator/conda-store/pull/518
- [x] Update repository URL in the docs and README - https://github.com/conda-incubator/conda-store/pull/518
- [x] Fix broken links in README - https://github.com/conda-incubator/conda-store/pull/518
- [ ] https://github.com/conda-incubator/conda-store/issues/519
```
