### ISSUE TITLE
META - Populate documentation with initial content

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#561]
This is the list of new documentation pages that need to be created. 

Convert the items to issues as you work on them to avoid overloading the issue tracker.

```[tasklist]
### conda-store
- [x] Introduction
- [ ] https://github.com/conda-incubator/conda-store/issues/566
- [ ] https://github.com/conda-incubator/conda-store/issues/568
- [x] Tutorial - Using shebang (https://conda-incubator.github.io/conda-store-ui/?path=/docs/docs-configuration--page)
- [x] How-to - Configure conda-store (https://conda.store/en/latest/administration.html#configuration)
- [ ] https://github.com/conda-incubator/conda-store/issues/569
- [x] Explanation - Resources and performance (https://conda.store/en/latest/administration.html#resource-requirements, https://conda.store/en/latest/administration.html#performance)
- [x] Explanation - Architecture (https://conda.store/en/latest/contributing.html#architecture)
- [x] Explanation - Databases (https://conda.store/en/latest/contributing.html#database)
- [x] https://github.com/conda-incubator/conda-store/issues/754
```

> **Note**
> **conda-store-ui tutorial section is blocked** on having automated screenshots using Playwright to keep the docs in sync with the rapid changes to the UI.

```[tasklist]
### conda-store-ui
- [x] Introduction
- [x] Tutorial - Install & Setup
- [x] Tutorial - Login/Logout
- [x] Tutorial - Create and edit envs
- [x] Tutorial - Delete envs - #563
- [x] Tutorial - Version control (switch to diff version)
- [x] How-to - Configure conda-store-ui (https://conda-incubator.github.io/conda-store-ui/?path=/docs/docs-configuration--page)
- [x] References - Storybook components
```

```[tasklist]
### jupyterlab-conda-store
- [x] Introduction - #752
- [x] Install & Setup - #752
```

```[tasklist]
### Community
- [ ] https://github.com/conda-incubator/conda-store/issues/399
- [x] Design assets -- xref: https://github.com/conda-incubator/conda-store-ui/issues/344
- [x] Contributing docs
- [x] Maintainer docs
```

**Comment by pavithraes** [comment]
All tasks except the REST API (already have a PR open) are done, so calling this META complete :)
