### ISSUE TITLE
[ENH] - Smooth the developer setup process

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#589]
### Feature description

If you are a developer who is working on a new feature in the conda-store-ui. The pattern is to 

* create a new conda env
  ```
  conda create --name conda-store-ui
  conda activate conda-store-ui
  conda install -c conda-forge yarn nodejs==16.14.2
  ```
* create an `.env` file with the appropriate values
* [if on a mac] change all instances of port 5000 to 8080 in `docker-compose-dev.yml` and `docker/assets/conda_store_config.py`
* launch the docker container `docker compose up -d `
* launch the webpack ui 
  ```
  yarn install
  yarn run build
  yarn run start
  ```

The old UI version of the UI from the latest build will then be available on 5000 (or 8080) at `http://localhost:5000/conda-store/` or `http://localhost:8080/conda-store/`. 

The new dev version will be available on `http://localhost:5001/` or `http://localhost:8081/`

### Value and/or benefit

There are some things I think we could improve here

* an `environment-dev.yml` to set up the env
* resolve the 5000 on mac problem
* get the docker compose to launch the new ui (I'm not sure I fully understand the process here)
* explain what is using the values in the .env file and how it relates to the docker-compose file and the new ui (i.e. why do I set 8080 in the .env but the new UI shows up on 8081?)

Some of these are just documentation, but some are improvements to the workflow in general. We may need to break these out into separate issues.

**Comment by costrouc** [comment]
Changing the default port in #642 will work towards this. There are additional things that need to be done. @dcmcand to look at later.

**Comment by kcpevey** [comment]
Chuck will focus on breaking down into separate issues and then move forward.

**Comment by kcpevey** [comment]
Consider the standalong implementation - discuss with @nkaretnikov

**Comment by dcmcand** [comment]
@kcpevey , this mainly references conda-store-ui. Should this be moved to the conda-store-ui repo?

**Comment by dcmcand** [comment]
Current status:
- [ ]     an environment-dev.yml to set up the env (#655)
- [X]     resolve the 5000 on mac problem (resolved by #642)
- [ ]     get the docker compose to launch the new ui (#656)
- [ ]     explain what is using the values in the .env file and how it relates to the docker-compose file and the new ui

I think we have some discussion needed about whether this belongs in this repo or the https://github.com/conda-incubator/conda-store-ui repo and what the scope for each project is.
