### ISSUE TITLE
[META] - Path length issues

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/conda-store#650]
Be it limitations in conda packaging or platform specificities, we can't just have arbitrary length for the environments and their contained files. This issue provides a big picture on these problems:

```[tasklist]
### General
- [ ] https://github.com/conda-incubator/conda-store/issues/649
- [ ] https://github.com/conda-incubator/conda-store/issues/611
```

```[tasklist]
### Windows-only
- [ ] https://github.com/conda-incubator/conda-store/issues/588
```

**Comment by nkaretnikov** [comment]
The issues linked above have been implemented and merged into main, closing.
