### ISSUE TITLE
META - Update migrated documentation

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#748]
Documentation was recently migrated into Docusaurus and new structure. This issue tracks updating various pages:

```[tasklist]
### conda-store
- [ ] Introduction (update with learning paths)
- [ ] How to - Standalone install
- [ ] How to - Docker installation
- [ ] How to - Kubernetes installation
- [ ] #727 (how-to)
- [ ] Tutorials - Using conda-store CLI
- [ ] Tutorials - Using conda-store as shebang (move from how-to)
- [ ] Explanations
- [ ] References - Architecture docs
```

```[tasklist]
### conda-store-ui
- [ ] Introduction (update with learning paths)
- [ ] Explanations - UI Components
- [ ] Tutorials - Admin-pages (when available)
```

```[tasklist]
### Community
- [ ] Contributing guidelines
```

**Comment by pavithraes** [comment]
Note to add the following section in conda-store-UI's how-to's around admin settings:

This was originally documented with artifacts, but removed in #726 

```
#### Existing Deployments

conda-store saves environment settings and doesn't automatically update them on
startup (see `CondaStore.ensure_settings`). Existing deployments need to
manually enable installer builds via the admin interface. This can be done by
going to `<CondaStoreServer.url_prefix>/admin/setting/<namespace>/<env>/` (or
clicking on the `Settings` button on the environment page) and adding
`"CONSTRUCTOR_INSTALLER"` to `build_artifacts`.

```
