### ISSUE TITLE
META - User experience research 

### ISSUE THREAD

**Issue by trallard** [conda-incubator/conda-store#751]
## Description

We have identified several gaps or needs to be addressed in conda-store workflows and, therefore, conda-store-ui. As such, we have identified the need to design and conduct UX studies to:

- Identify critical user workflows, unaddressed needs and priorities: individual users, team collaboration, cross-organisational collaboration
- Further improve role mappings, role-based access, and sharing workflows and mechanisms
- Improve existing workflows based on the learnings
- Define a CLI and local experience for individual users and teams

```[tasklist]
### Tasks
- [ ] Create key personas to tackle 
- [ ] Draft user stories corresponding to the personas 
- [ ] Design the user studies
- [ ] Run user studies
- [ ] Synthesise results and plan improvements
```

**Comment by trallard** [comment]
@smeragoel currently working on paperwork for studies

**Comment by peytondmurray** [comment]
I volunteer to test this!
