### ISSUE TITLE
[ENH] - Enable transferring/copying of full conda-store deployment

### ISSUE THREAD

**Issue by peytondmurray** [conda-incubator/conda-store#949]
### Feature description

Transferring or copying a full conda-store deployment is currently not possible. Add the ability to transfer or copy a complete conda-store deployment, including copying namespaces and environments, and recreation of active environments.

- [ ] Finish #889; transferring a deployment will require recreating archived environments.
- [ ] Determine the best way to maintain namespace/environment relationships; just copy the database?
- [ ] Add a function to the python API or the CLI that creates a single conda-store deployment into a `.tar.gz` containing the database and environment.yaml files
- [ ] Add a function to the python API or the CLI that turns the `.tar.gz` back into a fully functioning conda-store
- [ ] Add integration tests which copy an entire conda-store deployment

### Value and/or benefit

Transferring a conda-store deployment is a long-requested feature.
